theme: jekyll-theme-cayman
title: WallStreetBets Coin (WSB)
description: A cryptocurrency coin made for the WallStreetBets community.
keywords: "WSB, wsb coin, wallstreetbets coin, wsb crypto, wsbcoin, wallstreetbets, wsb crypto coin, wsb wallet"

url: "https://wsbcoin.cash"
plugins:
  - jekyll-sitemap

github:
  is_project_page: false
